apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyzdocker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ydocker
  template:
    metadata:
      labels:
        app: ydocker
    spec:
      containers:
      - name: xydockerrepos
        image: sampleapicr.azurecr.io/xydockerrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: ydocker
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: ydocker